name: Build and Deploy Functions

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/release*'

jobs:
  build:
    uses: ./.github/workflows/release-build.yaml

  deploy_dev:
    uses: ./.github/workflows/release-deploy.yaml
    needs: build
    with:
      environment: 'dev'
    secrets: inherit

  deploy_test:
    uses: ./.github/workflows/release-deploy.yaml
    needs: deploy_dev
    with:
      environment: 'test'
    secrets: inherit

  deploy_prod:
    uses: ./.github/workflows/release-deploy.yaml
    needs: deploy_test
    with:
      environment: 'prod'
    secrets: inherit