on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: '${{ inputs.environment }}'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: functions-artifact

      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Activity Functions App
        uses: Azure/functions-action@v1
        with:
          app-name: 'func-trippy-${{ inputs.environment }}-activity'
          package: 'activity'

      - name: Deploy to Participant Functions App
        uses: Azure/functions-action@v1
        with:
          app-name: 'func-trippy-${{ inputs.environment }}-participant'
          package: 'participant'

      - name: Deploy to Trip Functions App
        uses: Azure/functions-action@v1
        with:
          app-name: 'func-trippy-${{ inputs.environment }}-trip'
          package: 'trip'
